# Generated by Django 4.2.11 on 2024-03-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='program',
        ),
    ]
