# Generated by Django 4.2.11 on 2024-03-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_available',
        ),
    ]
