# Generated by Django 4.2.11 on 2024-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='remarks_on_return',
            field=models.CharField(default='', help_text='Book remarks/condition during return', max_length=100),
        ),
    ]
