version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: gunicorn lms.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ..:/usr/src/app
    ports:
      - "8080:8000"
    env_file:
      - ../lms/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40

  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
